### ISSUE TITLE
State of library

### ISSUE THREAD

**Issue by bangarharshit** [wealthfront/magellan#101]
Is this library maintained? I want to use it in a pet project but first, want to get a lot of open issues fixed. Will you guys be open to PR post discussions on those issues? Will be happy to give a shot in fixing most of these.

**Comment by ryanmoelter** [comment]
Hey! Sorry for the delay.

This library is still maintained, and we still use it in our production app. I personally plan to work on some new features soon, but I can't make guarantees on timelines. (If you're curious about how I'm prioritizing things, check out the projects tab and/or the milestones on issues.)

We'll definitely review any PRs you make, and in a more timely manner than this. Out of curiosity, which issues are the most important for you?
