### ISSUE TITLE
Exception while using the navigator.goBack()

### ISSUE THREAD

**Issue by JitainSharma** [wealthfront/magellan#179]
Platform : Android TV
OS : Android 29

When navigating from one screen to other using `navigator.goTo(Screen screen)` and using `navigator.goBack()` crash the app with exception:

java.lang.IllegalStateException: Can't go back, this is the last screen. Did you mean to call handleBack() instead?
        at com.wealthfront.magellan.Preconditions.checkState(Preconditions.java:43)
        at com.wealthfront.magellan.Navigator.goBack(Navigator.java:415)

**Comment by ryanmoelter** [comment]
Hmm, that's a strange exception to find during going back. Is there any chance that the backstack has been cleared or is empty for some reason? Also, what version of magellan are you using?

I want to help more, but it's hard to help with so little information. Is what you're working on open source, or could you make a small sample project to demonstrate the crash you're seeing?
