### ISSUE TITLE
Advanced sample

### ISSUE THREAD

**Issue by itsAmeAgain** [wealthfront/magellan#18]
The advanced sample is a mess, (my opinion)  the code is just generally unstructured, I think the addition of RXJava and Dagger has just complicated the example.

Please provide an example that uses no third party libraries and show cases switching views, back and forward, passing data between views, switching to an arbitrary view, lifecycle integrations etc, and is cleanly coded, to keep things clear. 

After all you claim this is the simplest navigation library!

**Comment by fabiendevos** [comment]
Thanks for your feedback, please note that this is still a work in progress. We are constantly working to improve this library and provide the best examples we can.
The advanced sample is meant to use those advanced libraries (hence, the name) and is still a work in progress, and not yet merged. Please refrain from opening issues on unmerged code.

Then simple sample is what you're looking for. Please see: https://github.com/wealthfront/magellan/tree/master/magellan-sample/src/main/java/com/wealthfront/magellan/sample

This simple example is also not perfect and we are working hard on improving it. If you have specific feedback on how to we can make it better, please suggest it (switching view is addressed, passing data can simply be done by passing a parameter in the constructor of a Screen).

**Comment by itsAmeAgain** [comment]
I didn't realize that advanced meant use third party libraries, i thought it meant a more "advanced" example of using your framework.

What I would like to see is a more complete example, how a real application can be structured using this framework only and some pattern like MV whatever, without the need for third party libraries, I mean butterknife is ok, but dagger and RxJava just complicated it, when you are trying to understand a new framework.

**Comment by fabiendevos** [comment]
Providing an example with data loaded from the network without Dagger and Rx is a bit painful, I am willing to consider it, but in the meantime can you either: 1) use the simpler example, or 2) look at the advanced one ignoring the Rx and Dagger stuff (just imaging you could not @Inject but pass the objects in the constructor instead, and not use Observables but use AsyncTasks?)
