### ISSUE TITLE
Clarity. Just trying to understand what makes this library any better than other libraries or fragments.

### ISSUE THREAD

**Issue by itsAmeAgain** [wealthfront/magellan#19]
From your wiki.

> Screens are not destroyed on rotation, or even when you navigate to the next screen. Therefore you need to be careful about not storing big objects in them, or leaking the context or the views.

```
final void destroyView() {
    saveViewState();
    activity = null;
    view = null;
  }
```
Does this not destroy the screen? I mean, the screen object is extended from viewgroup and you are destroying everything and saving the state when the view is changed and then recreating the screen object.

**Comment by wclausen** [comment]
Seems like you may be getting confused about the difference between Screens and Views. 

Screens contain your logic and are not destroyed on rotation. Screens do not extend ViewGroup, but rather are parameterized by a View type which extends ViewGroup. Screens are responsible for creating and destroying their Views (which are then shown/hidden by a Navigator during navigation). 

What you are seeing above in `destroyView()` is not the destruction of the Screen, but the destruction of the Screen's associated View. This method is called when navigating to a new view or on rotation, when the activity is destroyed.

**Comment by fabiendevos** [comment]
Thanks for your feedback, we will improve the documentation over time.
In the mean time, @wclausen gave a great explanation of what's going on.

**Comment by itsAmeAgain** [comment]
I already understood that it is a destruction of the view and not the screen, in the code sample I posted.

But what is a screen, really. It has methods to serialize and deserialize the state of the view, it also handles some lifecycle events. So how is that different from any view being serialized in the normal android framework? You are still destroying the view and saving the state and then creating it after, when a rotation occurs, in fact this Screen object is very similar to a fragment.

**Comment by fabiendevos** [comment]
A screen is akin to a Presenter in the MVP pattern. It handles the logic of your app, when the view purely handles the display (UI). The Screen is *not* serialized. 

You are absolutely correct that the Screen is very similar to a Fragment. Our hope is that it:
1. Has a simpler lifecycle
2. Gives you better control of the backstack
3. Survives screen rotation (Fragments only do this if you ask for this behavior)
4. Use synchronous navigation

And a few more convenience things. Overall hopefully much simpler to implement than using Fragments. But feel free to use Fragment if you prefer, and also consider other libraries such as conductor and scoop: each have their own unique advantages and drawbacks.

**Comment by itsAmeAgain** [comment]
Correct, I did not say the screen is serialized, I said

> It has methods to serialize and deserialize the state of the view

```
final void save(Bundle outState) {
    saveViewState();
    if (viewState != null) {
      outState.putSparseParcelableArray(VIEW_STATE + hashCode(), viewState);
    }
    viewState = null;
  }
```

Fragments need the setRetainInstance flag to keep them around on rotation but that is easily solved by serializing and deserializing your data much like you have done here., or using plain views.

What is the benefit of retaining the screen object after you have navigated away from it?

I wrote my own library that does navigation using views, it handles rotations and animations/transitions and saving the state of the view, but rather than keep the presenter or (screen as you call it) around on rotation or navigation, I simply re create the whole thing, i do not use generics or reflection(conductor), just vanilla views that extend my base view class.

**Comment by fabiendevos** [comment]
The benefit of keeping the screen is one of the biggest benefit of Magellan, it is clearly a strong decision and not everyone will agree with this, but it results in pretty amazing gain in productivity when developing Android apps. 
In particular, if you are willing to accept that the app restart from the first screen if the process is killed, then you can get away with no serialization stall anywhere, and just simply use fields and pass objects as simple parameters.

**Comment by Zhuinden** [comment]
@itsAmeAgain the purpose of retaining the view controller is to use the view controller as an explicit scope.

You can achieve the same thing with retained fragments.... or the newly introduced `ViewModel` things that are essentially retained fragments on top of your activity/fragment.

**Comment by fabiendevos** [comment]
Exactly. And it's correct that you can achieve the same thing with what you mentioned, just way harder in my opinion. :)
