### ISSUE TITLE
Are you guys not open to discussions?

### ISSUE THREAD

**Issue by itsAmeAgain** [wealthfront/magellan#21]
I just want to get a clarification before I post any more issues. Are you open to discuss the benefits of using this library vs other libraries and or vanila fragments/views and activities or am I wasting my time?

I like the premise of your library, but I am just trying to understand how or why its different from others,  and why I would want to use it, but if you don't care, then that's fine, I can move onto other things.

The reason I post this, is that all my attempts to open a discussion where closed.

**Comment by fabiendevos** [comment]
Hi,

I am the main author and I am more than happy to discuss the advantages and disadvantages of Magellan! The issues of a Github project, however, are not a good format for an open discussion, and will be closed if not a feature considered for future release or bug (for example, I will only close the issue you opened here: https://github.com/wealthfront/magellan/issues/17 when this is fixed). Let me see if I can setup a gitter for the project for discussion, in the meantime, please follow me on twitter: https://twitter.com/Fabien_Devos (and I ll follow back to DM) or tweet at me if you want a public discussion instead. If you don't have twitter, you can also email me at: leworgle [at] gmail.

Thanks again for your feedback and interest in this project. I want to stress again that this is a work in progress and still in active development.

**Comment by itsAmeAgain** [comment]
Ok thanks, a gitter would be great, I do not use twitter and its not ideal for a decent conversation.

**Comment by fabiendevos** [comment]
That's fine, feel free to email me and I'll try to setup gitter asap.
