### ISSUE TITLE
How to implement tabs in screen 

### ISSUE THREAD

**Issue by shakil807g** [wealthfront/magellan#25]
it is possible to create child screens in order to create tabs

**Comment by fabiendevos** [comment]
Hi @shakil807g,

Glad you asked! Yes it is totally possible and it is on our list of add-ons to open source!
It's still pretty easy to implement yourself as it is using [ScreenGroup](https://github.com/wealthfront/magellan/blob/master/magellan-library/src/main/java/com/wealthfront/magellan/ScreenGroup.java)

Do something like this:

`BaseTabsScreen.java`
```java
public class BaseTabsScreen extends ScreenGroup<Screen, TabsView> {

  public BaseTabsScreen(List<Screen> screens) {
    super(screens);
  }

  @Override
  protected TabsView createView(Context context) {
    return new TabsView(context, getScreens());
  }

  @Override
  protected void onShow(Context context) {
    super.onShow(context);
    for (Screen screen : getScreens()) {
      getView().addTabView(screen.getView());
    }
  }

}
```
`TabsView.java`

```java
public class TabsView extends BaseScreenView<BaseTabsScreen> {

  @BindView(R.id.tabLayout) TabLayout tabLayout;
  @BindView(R.id.pager) ViewPager pager;

  public TabsView(Context context) {
    super(context);
  }

  public TabsView(Context context, List<? extends Screen> tabScreens) {
    super(context);
    inflate(getContext(), R.layout.tabs, this);
    bind(this);
    initPager(context, tabScreens);
  }

  @VisibleForTesting
  public TabsView(Context context, List<? extends Screen> tabScreens, TabLayout tabLayout, ViewPager pager) {
    super(context);
    this.tabLayout = tabLayout;
    this.pager = pager;
    initPager(context, tabScreens);
  }

  private void initPager(Context context, List<? extends Screen> tabScreens) {
    TabsAdapter tabsAdapter = new TabsAdapter(context, tabScreens);
    pager.setAdapter(tabsAdapter);
    pager.addOnPageChangeListener(new TabLayoutOnPageChangeListener(tabLayout));

    tabLayout.setTabsFromPagerAdapter(tabsAdapter);
    tabLayout.setOnTabSelectedListener(new ViewPagerOnTabSelectedListener(pager));
  }

  public void addTabView(View view) {
    pager.addView(view);
  }

}
```

**Comment by mkodekar** [comment]
any idea how to make the tabsadapter ?

**Comment by mkodekar** [comment]
@fabiendevos can i know how the tabsadapter class made i had been trying and i am getting in to error

**Comment by fabiendevos** [comment]
Sure! Here is a simple implementation:

```java
public class TabsAdapter extends PagerAdapter {

  private final Context context;
  private final List<? extends Screen> tabScreens;

  public TabsAdapter(Context context, List<? extends Screen> tabScreens) {
    this.context = context;
    this.tabScreens = tabScreens;
  }

  @Override
  public Object instantiateItem(ViewGroup container, int position) {
    return tabScreens.get(position).getView();
  }

  @Override
  public void destroyItem(ViewGroup container, int position, Object object) {}

  @Override
  public int getCount() {
    return tabScreens.size();
  }

  @Override
  public boolean isViewFromObject(View v1, Object v2) {
    return v1 == v2;
  }

  @Override
  public CharSequence getPageTitle(int position) {
    return tabScreens.get(position).getTitle(context);
  }

}
```

**Comment by mkodekar** [comment]
Man i did exactly the same but with adding container.removeView, i will try it just now and let you know if it works

**Comment by mkodekar** [comment]
Thanks @fabiendevos this works in kotlin way as well

inner class TabsAdapter(val context: Context, val screenList: List<Screen<*>>) : PagerAdapter() {

        override fun isViewFromObject(view: View?, `object`: Any?) = view == `object`

        override fun getCount() = screenList.size

        override fun instantiateItem(container: ViewGroup?, position: Int): Any {
            return screenList[position].getView()
        }

        override fun destroyItem(container: ViewGroup?, position: Int, `object`: Any?) {}

        override fun getPageTitle(position: Int) = when(position) {
            1-> "Songs"
            2-> "Ablums"
            3-> "Artists"
            4-> "Playlists"
            else -> "Songs"
        }

    }

**Comment by fabiendevos** [comment]
Put the Java example on the wiki: https://github.com/wealthfront/magellan/wiki/Implementing-Tabs-or-other-%22Screens-into-a-Screen%22-UI%2C-using-ScreenGroup
