### ISSUE TITLE
Add sample app

### ISSUE THREAD

**Issue by fabiendevos** [wealthfront/magellan#3]

**Comment by wclausen** [comment]
#9

**Comment by MatthAddax** [comment]
Hi,

I just looked for the sample and I'm wondering, does every View need it's "Screen" and "BaseView"? ANd it looks like the "Screen" is "only" a builder who will tell the navigator which view he must display, isn't it? 

Thanks :)

**Comment by wclausen** [comment]
Every `Screen` should have a `View` (which commonly extends `BaseScreenView`, but could be any `ViewGroup` that implements `ScreenView`), and every `View` should have a `Screen`.

As for whether the `Screen` (i.e. `HomeScreen` class in the sample) is only a builder in the basic sample, that is not quite right. It is true that the `Screen` is responsible for creating a view and providing it to the `Navigator`, but the Screen is also responsible for the logic that happens in response to user input (i.e. the `HomeScreen` tells the `Navigator` to go to a `DetailScreen`). Those are the responsibilities of the `HomeScreen` in the sample.

In more complicated applications, the `Screen` would have those responsibilities outlined above, and it would also be responsible for fetching data from local storage/the network to show to the user.

The `View` is generally supposed to be "dumb" and simply connect Android UI elements to the proper place in the `Screen` (i.e. call `HomeScreen.defaultTransitionButtonClicked()` when the user clicks on the default transition button in the `HomeView`)

**Comment by wclausen** [comment]
More advanced sample app: #14 

Demonstrates:
- Dependency injection in `Screen` (see `TideDetailsScreen`)
- RxJava + Retrofit for network requests in `Screen`
