### ISSUE TITLE
sliding left to right

### ISSUE THREAD

**Issue by MahdiPishguy** [wealthfront/magellan#30]
Thanks to release this useful library, right to left is default of samples which i see them. how can i change that to left to right?

**Comment by fabiendevos** [comment]
Hi @MahdiPishguy ,

Happy you find this library useful.
To implement a different transition, it's extremely simple, just implement your own by implementing the `Transition` interface. See the [wiki page on Transitions](https://github.com/wealthfront/magellan/wiki/Transitions), and look [here](https://github.com/wealthfront/magellan/tree/master/magellan-library/src/main/java/com/wealthfront/magellan/transitions) for examples of implementations.

Hope this answer your question!

Thanks,

Fabien
