### ISSUE TITLE
How to hide toolbar?

### ISSUE THREAD

**Issue by notdrone** [wealthfront/magellan#31]
I'm trying to hide the toolbar from the detail screen by overriding `shouldShowActionBar()` in the sample provided, but it's still visible. I want to implement a custom toolbar on some Views. Is that possible?

**Comment by notdrone** [comment]
I changed the theme for the activity to `NoActionBar` and implemented the toolbars for each view. Is there a better way to do this?

**Comment by fabiendevos** [comment]
Hi @notdrone ,

You need to implement `NavigationListener` in your Activity, and implement the hiding / showing yourself for now. In the future, we hope to provide you with this automatically.

For example:
```java
  @Override
  public void onNavigate(ActionBarConfig actionBarConfig) {
    if (actionBarConfig.visible()) {
      actionBar.setVisibility(VISIBLE);
    } else {
      actionBar.setVisibility(GONE);
    }
  }
```

This is like this for now to avoid to force you to depend on the support lib.

**Comment by notdrone** [comment]
This is much better than what I was doing. Thanks a lot!
