### ISSUE TITLE
FloatingActionButton strange behavior

### ISSUE THREAD

**Issue by dimparf** [wealthfront/magellan#32]
Hi
I have two screens. Clicking on the fab shows the second one. By clicking the back, the first screen is displayed and fab button is shown at the top of the activity (strange behavior). After clicking, it moves to the desired location.
Gist for this strange behavior: https://gist.github.com/dimparf/d3c3314aa1248a5b33e78dedbc22ad40

**Comment by fabiendevos** [comment]
My guess is that it has to do with the RecyclerView in the middle?
Difficult to tell without the whole code. 
 doubt it's related to Magellan though.
