### ISSUE TITLE
Question: any plans to have a some kind of a PreferenceScreen?

### ISSUE THREAD

**Issue by theyann** [wealthfront/magellan#52]
Hello guys,

Just wondering, I'm working on a simple app that has preferences. The current "old" version uses PreferenceFragment which is quite practical.
I actually have never tried to put preferences in a view before and I did not find a way to do it. I find the PreferenceFragment system quite nice and easy.
Any plan on putting something together for this?

In the meantime, I guess my single activity no fragment app will have 2 activities and 1 fragment ;)

Thanks

Yannick

**Comment by fabiendevos** [comment]
I never bough into the PreferenceFragment / PreferenceActivty thing to be completely honest. :) It's so easy to simply have views and implement it yourself. And you always end up having to work around the framework for special case when you try to use the "one size fits all" PreferenceFragment.
For those reasons, a PreferenceScreen would go fairly low on my list. But if there is enough demand, for sure we can write one. Should be extremely easy.

**Comment by theyann** [comment]
ok, no problem.
