### ISSUE TITLE
Tabs screen with more than 2 screen bug

### ISSUE THREAD

**Issue by mkodekar** [wealthfront/magellan#53]
Screens in tablayout / the tab example having more than 2 tabs don't show any UI changes or even any views in them until and unless the screen is rotated or the activity's on create is called once again, maybe an implementation like fragmentstatepageradapter is need for screens @fabiendevos

**Comment by mkodekar** [comment]
@fabiendevos

**Comment by fabiendevos** [comment]
We use this implementation with 3 tabs in the app without any problem, but I think the example was missing:
`pager.setOffscreenPageLimit(Integer.MAX_VALUE);`
I fixed it on the wiki, let me know if that's enough.

In any case you're right we need an add-on lib for this. It's actually the next item on our roadmap.
