### ISSUE TITLE
Testing with espresso

### ISSUE THREAD

**Issue by mkodekar** [wealthfront/magellan#55]
Any idea on how to perform ui testing with espresso at this point of time i am justing going a screen at a time @fabiendevos

**Comment by fabiendevos** [comment]
Sure, we use espresso extensively in our app. No problem whatsoever: just click on whatever view / button you have to navigate to the next screen. Basically use espresso normally and it will work. If it doesn't please let me know what problem you're having. :)

**Comment by mkodekar** [comment]
activity rule I mean to say I always have to change to the screen I want to test in Navigator.with root()

**Comment by fabiendevos** [comment]
You shouldn't have to do that for true, highest level, UI tests (integration tests). Just start at your root Screen and click to reach whichever Screen you want to test.

But using the navigator directly to test a particular screen's UI is a valid use of it as well.

Not sure I answered your question though.

**Comment by mkodekar** [comment]
yep you are correct using navigator to test is the proper use.
