### ISSUE TITLE
Support for autodispose

### ISSUE THREAD

**Issue by bangarharshit** [wealthfront/magellan#62]
[Autodispose](https://github.com/uber/AutoDispose) is built around some of the limitations for `RxLifeCycle`.  I can send a PR for the support. It will have a module of its own.

**Comment by fabiendevos** [comment]
We have support for Rx 2 and an autoDispose already, although unreleased yet (should be soon): https://github.com/wealthfront/magellan/blob/master/magellan-rx2/src/main/java/com/wealthfront/magellan/rx2/RxScreen.java#L24

Does this solve the problem for you?

**Comment by bangarharshit** [comment]
Yeah. This is good enough for my usecase.
