### ISSUE TITLE
Multiple activites

### ISSUE THREAD

**Issue by Shakezulla57** [wealthfront/magellan#72]
Hello thanks for the library. Is there reason you couldn't have multiple activities (other than kind of defeating the purpose of this library)? Let's say you had some silos of functionality that could each have their own navigator running once you enter that activity. I'm curious about using this library to ease the pain of fragments but I don't want to be stuck down the line with some feature requirement that needs another activity.

**Comment by fabiendevos** [comment]
Hi @Shakezulla57 ,

> Is there reason you couldn't have multiple activities

Nope! You can totally have multiple activities, just have one navigator per activity.

> Let's say you had some silos of functionality that could each have their own navigator running once you enter that activity. I'm curious about using this library to ease the pain of fragments but I don't want to be stuck down the line with some feature requirement that needs another activity.

This is a totally valid usecase of Magellan, which hopefully should really help you! I will try to add a wiki page on that specifically.

You should be able to just go for it and use Magellan as is, but if you run into trouble (or if you find out important gotchas in the process), please report back here!

**Comment by fabiendevos** [comment]
I added a section in the wiki under Single Activity Architecture, and it was already in the FAQ so I am going to close this for now, feel free to reopen if you find an issue or if you think this use case should be called out somewhere else.
