### ISSUE TITLE
Consider allowing nested navigation with Magellan Navigators

### ISSUE THREAD

**Issue by JPrez38** [wealthfront/magellan#91]
Currently you can only use one navigator because inside of Navigator.java, the container for the navigator is set in the onCreateView method with always finds the view magellan_container on the main activity. Navigators could theoretically be able to have more flexibility and could be nested insider, aka, if you wanted to manage a flow inside of another screen similar to how fragments work. To do this though, we would have to be able to set a view for the container on the navigator.

**Comment by ryanmoelter** [comment]
Done in 2.0
